SportsStore/Components/CartSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components
{
    public class CartSummaryViewComponent: ViewComponent
    {
        private Cart cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

SportsStore/Components/NavigationMenuViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
 using SportsStore.Models;

namespace SportsStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IProductRepository repository;

        public NavigationMenuViewComponent(IProductRepository repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];  

            return View(repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

SportsStore/Views/Shared/ProductSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Product

<div class="card card-outline-primary m-1 p-1">
    <div class ="bg-faded p-1">
         <h4>
             @Model.Name
             <span class="badge badge-pill badge-primary" style="float:right">
                 <small>@Model.Price.ToString("c")</small>
             </span>
        </h4>
     </div>
    <form id="@Model.ProductID" asp-action="AddToCart"
          asp-controller="Cart" method="post">
        <input type="hidden" asp-for="ProductID" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            @Model.Category
            <button type="submit" class="btn btn-success btn-sm pull-right" style="float:right">
                Add To Cart
            </button>
        </span>
    </form>


    <div class="card-text p-1">Category : @Model.Category</div>
 </div>
 

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css"
          asp-href-exclude="**/*-reboot*, **/*-grid*" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

    <title>SportsStore</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <div class="row">
            <a class="col navbar-brand" href="#">SPORTS STORE</a>
            <div class=" ="col-4 text-right"  style="color:white" >
                @await  Component.InvokeAsync("CartSummary")
             </div>
        </div>
    </div>
    
    <div id="bodyContainer" style="width:50%; margin: 0 auto" >
        <div class="row panel "  style="margin: 0 auto" >
            <div id="categories" class="col-xs-3" style="width:20%">
                @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col-xs-8" style="width:75%">
            @RenderBody()
        </div>
        </div>
    </div>
</body>
</html>